export const GET_MY_CRYPTOS = 'GET_MY_CRYPTOS';

export const GET_MY_CRYPTOS_SUCCESS = 'GET_MY_CRYPTOS_SUCCESS';

export const GET_MY_CRYPTOS_FAILURE = 'GET_MY_CRYPTOS_FAILURE';


export const ADD_MY_CRYPTOS = 'ADD_MY_CRYPTOS';

export const ADD_MY_CRYPTOS_SUCCESS = 'ADD_MY_CRYPTOS_SUCCESS';

export const ADD_MY_CRYPTOS_FAILURE = 'ADD_MY_CRYPTOS_FAILURE';



export const REMOVE_MY_CRYPTOS = 'REMOVE_MY_CRYPTOS';

export const REMOVE_MY_CRYPTOS_SUCCESS = 'REMOVE_MY_CRYPTOS_SUCCESS';

export const REMOVE_MY_CRYPTOS_FAILURE = 'REMOVE_MY_CRYPTOS_FAILURE';
